name: sdk-stack

x-core-dependencies: &core_dependencies
  redis:
    condition: service_healthy
  master:
    condition: service_healthy
  filer:
    condition: service_healthy
  volume:
    condition: service_healthy
  s3:
    condition: service_healthy
  s3-ttl-configure:
    condition: service_completed_successfully

services:
  ################################
  # Необходимые сервисы (Redis + S3)
  ################################

  redis:
    image: redis:7-alpine
    container_name: EnviRedisBroker
    restart: always
    #command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
    networks:
      - sdk-net
    volumes:
      - ./redis_data:/data
    deploy:
      resources:
        limits:
          memory: 2024M
          cpus: "1"

  master:
    image: chrislusf/seaweedfs:4.06
    command: "master -ip=master -ip.bind=0.0.0.0 -port=9333 -port.grpc=19333"
    ports:
      - "9333:9333"   # Web UI + API
      - "9321:9321"   # Metrics
      - "19333:19333" # gRPC
    volumes:
      - s3_master_data:/data
    networks:
      - sdk-net
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:9333/cluster/status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  volume:
    image: chrislusf/seaweedfs:4.06
    command: "volume -mserver=master:9333 -port=8080 -dir=/data1 -ip=volume -ip.bind=0.0.0.0"
    volumes:
      - ./s3_storage_data:/data1
    depends_on:
      master:
        condition: service_healthy
    ports:
      - "8080:8080"  # API
      - "9322:9322"  # Metrics
      - "18080:18080"
    networks:
      - sdk-net
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8080/status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  filer:
    image: chrislusf/seaweedfs:4.06
    command: "filer -master=master:9333 -port=8888 -ip.bind=0.0.0.0 -port.grpc=18888"
    depends_on:
      master:
        condition: service_healthy
    ports:
      - "8888:8888"
      - "18888:18888"
    networks:
      - sdk-net
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8888/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  s3:
    image: chrislusf/seaweedfs:4.06
    entrypoint: [ "/bin/sh", "/setup_s3/s3-entrypoint.sh" ]
    command:
      - s3
      - -filer=filer:8888
      - -ip.bind=0.0.0.0
      - -config=/etc/seaweedfs/s3.json
    env_file:
      - docker.env
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8333" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - "8333:8333"
    volumes:
      - ./setup_s3/s3-entrypoint.sh:/setup_s3/s3-entrypoint.sh:ro
    depends_on:
      filer:
        condition: service_healthy
      master:
        condition: service_healthy
      volume:
        condition: service_healthy
    networks:
      - sdk-net
    restart: always

  s3-ttl-configure:
    image: chrislusf/seaweedfs:4.06
    volumes:
      - ./setup_s3/s3-configure.sh:/setup_s3/s3-configure.sh:ro
    env_file:
      - docker.env
    environment:
      BUCKET_TTLS_JSON: '{"video-frames":"3m","inference":"3m"}'
    entrypoint: [ "/bin/sh" ]
    command: [ "/setup_s3/s3-configure.sh" ]
    depends_on:
      filer:
        condition: service_healthy
      s3:
        condition: service_healthy
    restart: "no"
    networks:
      - sdk-net

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    networks:
      - sdk-net

#  data_reader:
#    image: sdk:v1
#    volumes:
#      - ./video:/video
#      - /services:/services
#    command: python /services/data_reader/app.py
#    container_name: EnviDataReader
#    environment:
#      - .env
#    networks:
#      - sdk_net
#    deploy:
#      resources:
#        limits:
#          memory: 200M    # Ограничение по памяти в 100 МБ
#          cpus: "0.5"
#
#  data_router:
#    image: sdk:v1
#    volumes:
#      - /services:/services
#    command: python /services/data_router/app.py
#    container_name: EnviDataRouter
#    environment:
#      - .env
#    networks:
#      - sdk_net
#    depends_on:
#      - data_reader
#    deploy:
#      resources:
#        limits:
#          memory: 200M    # Ограничение по памяти в 100 МБ
#          cpus: "0.5"



volumes:
  s3_master_data:
  redis_data:

networks:
  sdk-net:
    driver: bridge