version: '3.7'
services:
  master:
    image: chrislusf/seaweedfs:3.93
    command: "master -ip=master -mdir=/data -peers=master:9333 "
    ports:
      - "9333:9333"  # Web UI + API
      - "19333:19333" # gRPC
    volumes:
      - master_data:/data
    networks:
      - seaweed-net

  volume1:
    image: chrislusf/seaweedfs:3.93
    command: "volume -mserver=master:9333 -port=8080 -dir=/data1"
    volumes:
      - ./volume1_data:/data1
    depends_on:
      - master
    ports:
      - "8080:8080"  # API
      - "18080:8081" # Web UI
    environment:
      - writers=256
    networks:
      - seaweed-net

  # Filer сервер (HTTP API + S3)
  filer:
    image: chrislusf/seaweedfs:3.93
    command: "filer -master=master:9333 -volume=volume1:8888"
    depends_on:
      - master
    ports:
      - "8888:8888"   # Web UI
      - "8333:8333"   # S3 API
    networks:
      - seaweed-net

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: "-js"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

#  data_reader:
#    image: sdk:v1
#    volumes:
#      - ./video:/video
#      - /services:/services
#    command: python /services/data_reader/app.py
#    container_name: EnviDataReader
#    environment:
#      - .env
#    networks:
#      - sdk_net
#    deploy:
#      resources:
#        limits:
#          memory: 200M    # Ограничение по памяти в 100 МБ
#          cpus: "0.5"
#
#  data_router:
#    image: sdk:v1
#    volumes:
#      - /services:/services
#    command: python /services/data_router/app.py
#    container_name: EnviDataRouter
#    environment:
#      - .env
#    networks:
#      - sdk_net
#    depends_on:
#      - data_reader
#    deploy:
#      resources:
#        limits:
#          memory: 200M    # Ограничение по памяти в 100 МБ
#          cpus: "0.5"



volumes:
  master_data:
  volume1_data:

networks:
  seaweed-net:
    driver: bridge